services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      SECRET_KEY : ""
      MYSQL_DATABASE_USER: "root"
      MYSQL_DATABASE_PASSWORD : "password"
      MYSQL_DATABASE_DB : "github_mole"
      MYSQL_DATABASE_HOST: "db"
      GITHUB_OAUTH_CLIENT_ID : ""
      GITHUB_OAUTH_CLIENT_SECRET : ""
      GITHUB_HOSTNAME : "https://github.com"
      GITHUB_API_URL :  "https://api.github.com"
    networks:
      - local-network
      
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "github_mole"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - local-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - db
      - backend
    environment:
      VITE_BACKEND_URL: "http://localhost:5000"
    networks:
      - local-network

volumes:
  db_data:

networks:
  local-network:
    driver: bridge
