from datetime import datetime
from app.database import db

class GitHubUserData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    github_login = db.Column(db.String(100), nullable=False)
    semester = db.Column(db.String(100), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lifetime = db.Column(db.Integer)
    start_at = db.Column(db.DateTime)
    end_at = db.Column(db.DateTime)
    period = db.Column(db.Integer)

    private_contributions = db.Column(db.Integer)
    commits = db.Column(db.Integer)
    issues = db.Column(db.Integer)
    gists = db.Column(db.Integer)
    prs = db.Column(db.Integer)
    pr_reviews = db.Column(db.Integer)
    repository_discussions = db.Column(db.Integer)
    commit_comments = db.Column(db.Integer)
    issue_comments = db.Column(db.Integer)
    gist_comments = db.Column(db.Integer)
    repository_discussion_comments = db.Column(db.Integer)
    repos = db.Column(db.Integer)

    a_count = db.Column(db.Integer)
    a_fork_count = db.Column(db.Integer)
    a_stargazer_count = db.Column(db.Integer)
    a_watcher_count = db.Column(db.Integer)
    a_total_size = db.Column(db.BigInteger)
    a_langs = db.Column(db.Integer)

    b_count = db.Column(db.Integer)
    b_fork_count = db.Column(db.Integer)
    b_stargazer_count = db.Column(db.Integer)
    b_watcher_count = db.Column(db.Integer)
    b_total_size = db.Column(db.BigInteger)
    b_langs = db.Column(db.Integer)

    c_total_count = db.Column(db.Integer)
    c_fork_count = db.Column(db.Integer)
    c_stargazer_count = db.Column(db.Integer)
    c_watcher_count = db.Column(db.Integer)
    c_total_size = db.Column(db.BigInteger)
    c_langs = db.Column(db.Integer)

    d_total_count = db.Column(db.Integer)
    d_fork_count = db.Column(db.Integer)
    d_stargazer_count = db.Column(db.Integer)
    d_watcher_count = db.Column(db.Integer)
    d_total_size = db.Column(db.BigInteger)
    d_langs = db.Column(db.Integer)