type TableHeaders = {
    [key: string]: string[];
  };

export const contributions = [
    "Commit Comments",
    "Gist Comments",
    "Issue Comments",
    "Repository Discussion Comments",
    "Gists",
    "Issues",
    "Pull Requests",
    "Repository Discussions",
    "Owned Original Repo",
    "Owned Forked Repo",
    "Collaborating Original Repo",
    "Collaborating Forked Repo",
  ];



  export const languages = [
    "Python",
    "Java",
    "Go",
    "JavaScript",
    "C++",
    "TypeScript",
    "PHP",
    "Ruby",
    "C",
    "C#",
    "Nix",
    "Shell",
    "Rust",
    "Scala",
    "Kotlin",
    "Swift",
    "Dart",
    "Perl",
    "Lua",
    "All",
  ];

  export const teamTableHeaders = ["GitHub ID","Age (days)","Commits","Comments","PRs & Issues","Lang Counts","Pop Lang Size","Repos"];

  export const userQueryHeaders = ["Dataset Name","Data Type","Start Time","End Time", "Queried At"];

  export  const tableHeaders: TableHeaders = { 	
    Contributions:["GitHub ID","Name","Email","Created At","Age (days)","Bio","Company",
        "Watching",
        "Starred Repositories",
        "Following",
        "Followers",
        "Private Contributions",
        "Commits",
        "Gists",
        "Issues",
        "Projects",
        "Pull Requests",
        "Pull Request Reviews",
        "Repositories",
        "Repository Discussions",
        "Commit Comments",
        "Issue Comments",
        "Gist Comments",
        "Repository Discussion Comments",
        "Owned Original Repo",	"Owned Original Repo Size",	"Owned Original Repo Selected Langs Size", "Owned Original Repo Langs Number",
        "Owned Forked Repo", "Owned Forked Repo Size",	"Owned Forked Repo Selected Langs Size", "Owned Forked Repo Langs Number",
        "Collaborating Original Repo",	"Collaborating Original Repo Size",	"Collaborating Original Repo Selected Langs Size", "Collaborating Original Repo Langs Number",
        "Collaborating Forked Repo", "Collaborating Forked Repo Size",	"Collaborating Forked Repo Selected Langs Size", "Collaborating Forked Repo Langs Size Number",
        "Total Langs Number"
    ],
    "Commit Comments":["GitHub ID","Created At","Body Text"],	
    "Gist Comments":["GitHub ID","Created At","Body Text"],
    "Issue Comments":["GitHub ID","Created At","Body Text"],
    "Repository Discussion Comments":["GitHub ID","Created At","Body Text"],
    "Gists":["GitHub ID","Created At","Description"],
    "Issues":["GitHub ID","Created At","Body Text","Title"],
    "Pull Requests":["GitHub ID","Created At","Body Text"],
    "Repository Discussions":["GitHub ID","Created At","Body Text"],
    "Owned Original Repo":["GitHub ID","Name","Created At","Updated At","Primary Language","Language Stats"],
    "Owned Forked Repo":["GitHub ID","Name","Created At","Updated At","Primary Language","Language Stats"],
    "Collaborating Original Repo":["GitHub ID","Name","Created At","Updated At","Primary Language","Language Stats"],
    "Collaborating Forked Repo":["GitHub ID","Name","Created At","Updated At","Primary Language","Language Stats"],
  }

  export const repoTypes: string[] = [
    "Owned Original Repo",
    "Owned Forked Repo",
    "Collaborating Original Repo",
    "Collaborating Forked Repo"];
    
  export const commitTableHeaders = [
    "Repository",
    "Author",
    "Author Email",
    "Author Login",
    "Branch",
    "Authored Date",
    "Changed Files",
    "Additions",
    "Deletions",
    "Message",
    "Parents",
    "Languages",
  ];

  export  const viewTableHeaders: { [key: string]: string[] } = { 	
    "total":["GitHub ID","Name","Email","Created At","Age (days)","Bio","Company",
    "Watching",
    "Starred Repositories",
    "Following",
    "Followers",
    "Private Contributions",
    "Commits",
    "Gists",
    "Issues",
    "Projects",
    "Pull Requests",
    "Pull Request Reviews",
    "Repositories",
    "Repository Discussions",
    "Commit Comments",
    "Issue Comments",
    "Gist Comments",
    "Repository Discussion Comments",
    "Selected Languages",
    "Owned Original Repo",	"Owned Original Repo Size",	"Owned Original Repo Selected Langs Size", "Owned Original Repo Langs Number",
    "Owned Forked Repo", "Owned Forked Repo Size",	"Owned Forked Repo Selected Langs Size", "Owned Forked Repo Langs Number",
    "Collaborating Original Repo",	"Collaborating Original Repo Size",	"Collaborating Original Repo Selected Langs Size", "Collaborating Original Repo Langs Number",
    "Collaborating Forked Repo", "Collaborating Forked Repo Size","Collaborating Forked Repo Selected Langs Size", "Collaborating Forked Repo Langs Size Number","Total Langs Number"],
    "Commit Comments":["GitHub ID","Created At","Body Text"],	
    "Gist Comments":["GitHub ID","Created At","Body Text"],
    "Issue Comments":["GitHub ID","Created At","Body Text"],
    "Repository Discussion Comments":["GitHub ID","Created At","Body Text"],
    "Repo Commits":["Repository","Author","Author Email","Author Login","Branch","Authored Date","Changed Files","Additions","Deletions","Message","Parents","Languages",],
    "User Commits":["Repository","Author","Author Email","Author Login","Branch","Authored Date","Changed Files","Additions","Deletions","Message","Parents","Languages",],
    "Gists":["GitHub ID","Created At","Description"],
    "Issues":["GitHub ID","Created At","Body Text","Title"],
    "Pull Requests":["GitHub ID","Created At","Body Text"],
    "Repository Discussions":["GitHub ID","Created At","Body Text"],
    "Repositories":["GitHub ID","Repository Type","Name","Created At","Updated At","Primary Language","Language Stats"],
  }

  export const headerToFieldMap: { [key: string]: string } = {
    "GitHub ID": 'author_github_login',
    "Name": 'name',
    "Email": 'email',
    "Created At": 'created_at',
    "Age (days)": 'age',
    "Bio": 'bio',
    "Company": 'company',
    "Watching": 'watching',
    "Starred Repositories": 'starred_repo',
    "Following": 'following',
    "Followers": 'followers',
    "Commits": 'commits',
    "Private Contributions": 'private_contrib',
    "Gists": 'gists',
    "Issues": 'issues',
    "Projects": 'projects',
    "Pull Requests": 'pull_requests',
    "Pull Request Reviews": 'pull_request_reviews',
    "Repositories": 'repositories',
    "Repository Discussions": 'repo_discussions',
    "Commit Comments": 'commit_comments',
    "Issue Comments": 'issue_comments',
    "Gist Comments": 'gist_comments',
    "Repository Discussion Comments": 'repo_discussion_comments',
    "Selected Languages": 'selected_langs',
    "Owned Original Repo": 'owned_original_repo',
    "Owned Original Repo Size": 'owned_original_repo_size',
    "Owned Original Repo Selected Langs Size": 'owned_original_repo_selected_langs_size',
    "Owned Original Repo Langs Number": 'owned_original_repo_langs_number',
    "Owned Forked Repo": 'owned_forked_repo',
    "Owned Forked Repo Size": 'owned_forked_repo_size',
    "Owned Forked Repo Selected Langs Size": 'owned_forked_repo_selected_langs_size',
    "Owned Forked Repo Langs Number": 'owned_forked_repo_langs_number',
    "Collaborating Original Repo": 'collaborating_original_repo',
    "Collaborating Original Repo Size": 'collaborating_original_repo_size',
    "Collaborating Original Repo Selected Langs Size": 'collaborating_original_repo_selected_langs_size',
    "Collaborating Original Repo Langs Number": 'collaborating_original_repo_langs_number',
    "Collaborating Forked Repo": 'collaborating_forked_repo',
    "Collaborating Forked Repo Size": 'collaborating_forked_repo_size',
    "Collaborating Forked Repo Selected Langs Size": 'collaborating_forked_repo_selected_langs_size',
    "Collaborating Forked Repo Langs Size Number": 'collaborating_forked_repo_langs_size_number',
    "Total Langs Number": 'total_langs_number',
    "Body Text": 'body_text',
    "Title": 'title',
    "Description": 'description',
    "Updated At":'updated_at',
    "Primary Language":'primary_language',
    "Language Stats":'languages',
    "Repository Type": 'repository_type',
    "Repository":"repo_name",
    "Author":"author_name",
    "Author Email":"author_email",
    "Author Login":"author_login",
    "Branch":"branch",
    "Authored Date":"authored_date",
    "Changed Files":"changed_files",
    "Additions":"additions",
    "Deletions":"deletions",
    "Message":"message",
    "Parents":"parent_count",
    "Languages":"lang_stats",
  };

  export const numericalValue: { [key: string]: boolean } = {
    "GitHub ID": true,
    "Age (days)": true,
    "Watching": true,
    "Starred Repositories": true,
    "Following": true,
    "Followers": true,
    "Private Contributions": true,
    "Commits": true,
    "Gists": true,
    "Issues": true,
    "Projects": true,
    "Pull Requests": true,
    "Pull Request Reviews": true,
    "Repositories": true,
    "Repository Discussions": true,
    "Commit Comments": true,
    "Issue Comments": true,
    "Gist Comments": true,
    "Repository Discussion Comments": true,
    "Owned Original Repo": true,
    "Owned Original Repo Size": true,
    "Owned Original Repo Selected Langs Size": true,
    "Owned Original Repo Langs Number": true,
    "Owned Forked Repo": true,
    "Owned Forked Repo Size": true,
    "Owned Forked Repo Selected Langs Size": true,
    "Owned Forked Repo Langs Number": true,
    "Collaborating Original Repo": true,
    "Collaborating Original Repo Size": true,
    "Collaborating Original Repo Selected Langs Size": true,
    "Collaborating Original Repo Langs Number": true,
    "Collaborating Forked Repo": true,
    "Collaborating Forked Repo Size": true,
    "Collaborating Forked Repo Selected Langs Size": true,
    "Collaborating Forked Repo Langs Size Number": true,
    "Total Langs Number": true,
    "Body Text Length": true,
    "Description length": true,
  };

  export const COLORS = [
    "#0088FE",
    "#00C49F",
    "#FFBB28",
    "#FF8042",
    "#FF6384",
    "#36A2EB",
    "#FFCE56",
    "#4BC0C0",
    "#A569BD",
    "#F39C12",
    "#D35400",
    "#1ABC9C",
    "#2ECC71",
    "#3498DB",
    "#9B59B6",
    "#E74C3C",
    "#0074D9",
    "#2ECC40",
    "#FFDC00",
    "#FF851B",
    "#FF4136",
    "#7FDBFF",
    "#B10DC9",
    "#3D9970",
  ];