"""
This module defines constants for field names used in GraphQL queries.

These constants represent various fields that can be queried from the GitHub GraphQL API.
Using constants helps to avoid typos and makes the code more maintainable.
"""

FIELD_ADDITIONS = "additions"
FIELD_AUTHORED_DATE = "authoredDate"
FIELD_AVATARURL = "avatarUrl"
FIELD_BIO = "bio"
FIELD_BODY_TEXT = "bodyText"
FIELD_CHANGED_FILES_IF_AVAILABLE = "changedFilesIfAvailable"
FIELD_COLOR = "color"
FIELD_COMPANY = "company"
FIELD_CONTRIBUTION_COUNT = "contributionCount"
FIELD_CONTRIBUTION_YEARS = "contributionYears"
FIELD_COST = "cost"
FIELD_CREATED_AT = "createdAt"
FIELD_DATE = "date"
FIELD_DELETIONS = "deletions"
FIELD_DESCRIPTION = "description"
FIELD_EMAIL = "email"
FIELD_END_CURSOR = "endCursor"
FIELD_ENDED_AT = "endedAt"
FIELD_HAS_NEXT_PAGE = "hasNextPage"
FIELD_ID = "id"
FIELD_OID = "oid"
FIELD_IS_BOUNTY_HUNTER = "isBountyHunter"
FIELD_IS_CAMPUS_EXPERT = "isCampusExpert"
FIELD_IS_DEVELOPER_PROGRAM_MEMBER = "isDeveloperProgramMember"
FIELD_IS_EMPLOYEE = "isEmployee"
FIELD_IS_EMPTY = "isEmpty"
FIELD_IS_GITHUB_STAR = "isGitHubStar"
FIELD_IS_HIREABLE = "isHireable"
FIELD_IS_SITE_ADMIN = "isSiteAdmin"
FIELD_LIMIT = "limit"
FIELD_LOGIN = "login"
FIELD_MESSAGE = "message"
FIELD_NAME = "name"
FIELD_OCCURRED_AT = "occurredAt"
FIELD_REMAINING = "remaining"
FIELD_RESET_AT = "resetAt"
FIELD_RESTRICTED_CONTRIBUTIONS_COUNT = "restrictedContributionsCount"
FIELD_SIZE = "size"
FIELD_STARTED_AT = "startedAt"
FIELD_TITLE = "title"
FIELD_TOTAL_COMMIT_CONTRIBUTIONS = "totalCommitContributions"
FIELD_TOTAL_COUNT = "totalCount"
FIELD_TOTAL_ISSUE_CONTRIBUTIONS = "totalIssueContributions"
FIELD_TOTAL_PULL_REQUEST_CONTRIBUTIONS = "totalPullRequestContributions"
FIELD_TOTAL_PULL_REQUEST_REVIEW_CONTRIBUTIONS = "totalPullRequestReviewContributions"
FIELD_TOTAL_REPOSITORY_CONTRIBUTIONS = "totalRepositoryContributions"
FIELD_TOTAL_SIZE = "totalSize"
FIELD_UPDATED_AT = "updatedAt"
FIELD_USED = "used"
FIELD_WEEKDAY = "weekday"

# Query node names
NODE_USER = "user"
NODE_VIEWER = "viewer"
NODE_WATCHING = "watching"
NODE_STARRED_REPOSITORIES = "starredRepositories"
NODE_FOLLOWING = "following"
NODE_FOLLOWERS = "followers"
NODE_GISTS = "gists"
NODE_ISSUES = "issues"
NODE_PROJECTS = "projects"
NODE_PULL_REQUESTS = "pullRequests"
NODE_REPOSITORIES = "repositories"
NODE_REPOSITORY_DISCUSSIONS = "repositoryDiscussions"
NODE_GIST_COMMENTS = "gistComments"
NODE_ISSUE_COMMENTS = "issueComments"
NODE_COMMIT_COMMENTS = "commitComments"
NODE_REPOSITORY_DISCUSSION_COMMENTS = "repositoryDiscussionComments"
NODE_CONTRIBUTIONS_COLLECTION = "contributionsCollection"
NODE_CONTRIBUTION_CALENDAR = "contributionCalendar"
NODE_WEEKS = "weeks"
NODE_CONTRIBUTION_DAYS = "contributionDays"
NODE_JOINED_GITHUB_CONTRIBUTION = "joinedGitHubContribution"
NODE_EDGES = "edges"
NODE_NODE = "node"
NODE_NODES = "nodes"
NODE_PAGE_INFO = "pageInfo"
NODE_LANGUAGES = "languages"
NODE_RATE_LIMIT = "rateLimit"
NODE_REPOSITORY = "repository"
NODE_PRIMARY_LANGUAGE = "primaryLanguage"
NODE_DEFAULT_BRANCH_REF = "defaultBranchRef"
NODE_TARGET = "target"
NODE_AUTHOR = "author"
NODE_HISTORY = "history"
NODE_ON = "... on "
NODE_COMMIT = "Commit"
NODE_PARENTS = "parents (first: 2)"
NODE_REFS = "refs"
NODE_REF = "ref"
NODE_OWNER = "owner"

# Argument names for GraphQL queries
ARG_LOGIN = "login"
ARG_FIRST = "first"
ARG_IS_FORK = "isFork"
ARG_OWNER_AFFILIATIONS = "ownerAffiliations"
ARG_ORDER_BY = "orderBy"
ARG_FIELD = "field"
ARG_DIRECTION = "direction"
ARG_FROM = "from"
ARG_TO = "to"
ARG_DRYRUN = "dryRun"
ARG_OWNER = "owner"
ARG_NAME = "name"
ARG_AUTHOR = "author"
ARG_REF_PREFIX = "refPrefix"
ARG_QUALIFIED_NAME = "qualifiedName"
