"""
This module defines constants for field names used in GraphQL queries.

These constants represent various fields that can be queried from the GitHub GraphQL API.
Using constants helps to avoid typos and makes the code more maintainable.
"""

# Field names for GraphQL queries
# RateLimit & QueryCost queries
FIELD_LIMIT = "limit"
FIELD_COST = "cost"
FIELD_REMAINING = "remaining"
FIELD_RESET_AT = "resetAt"
FIELD_USED = "used"

# UserLoginViewer & UserProfileStats queries & UserLogin
FIELD_LOGIN = "login"
FIELD_NAME = "name"
FIELD_ID = "id"
FIELD_EMAIL = "email"
FIELD_CREATED_AT = "createdAt"
FIELD_BIO = "bio"
FIELD_COMPANY = "company"
FIELD_AVATARURL = "avatarUrl"

FIELD_TOTAL_COUNT = "totalCount"
FIELD_SIZE = "size"
FIELD_NAME = "name"
FIELD_BODY_TEXT = "bodyText"
FIELD_DESCRIPTION = "description"
FIELD_TITLE = "title"
FIELD_END_CURSOR = "endCursor"
FIELD_HAS_NEXT_PAGE = "hasNextPage"
FIELD_STARTED_AT = "startedAt"
FIELD_ENDED_AT = "endedAt"
FIELD_RESTRICTED_CONTRIBUTIONS_COUNT = "restrictedContributionsCount"
FIELD_TOTAL_COMMIT_CONTRIBUTIONS = "totalCommitContributions"
FIELD_TOTAL_ISSUE_CONTRIBUTIONS = "totalIssueContributions"
FIELD_TOTAL_PULL_REQUEST_CONTRIBUTIONS = "totalPullRequestContributions"
FIELD_TOTAL_PULL_REQUEST_REVIEW_CONTRIBUTIONS = "totalPullRequestReviewContributions"
FIELD_TOTAL_REPOSITORY_CONTRIBUTIONS = "totalRepositoryContributions"


FIELD_UPDATED_AT = "updatedAt"
FIELD_OCCURRED_AT = "occurredAt"
FIELD_IS_BOUNTY_HUNTER = "isBountyHunter"
FIELD_IS_CAMPUS_EXPERT = "isCampusExpert"
FIELD_IS_DEVELOPER_PROGRAM_MEMBER = "isDeveloperProgramMember"
FIELD_IS_EMPLOYEE = "isEmployee"
FIELD_IS_GITHUB_STAR = "isGitHubStar"
FIELD_IS_HIREABLE = "isHireable"
FIELD_IS_SITE_ADMIN = "isSiteAdmin"

FIELD_IS_EMPTY = "isEmpty"
FIELD_SIZE = "size"
FIELD_TOTAL_SIZE = "totalSize"
FIELD_AUTHORED_DATE = "authoredDate"
FIELD_CHANGED_FILES_IF_AVAILABLE = "changedFilesIfAvailable"
FIELD_ADDITIONS = "additions"
FIELD_DELETIONS = "deletions"
FIELD_MESSAGE = "message"

FIELD_DATE = "date"
FIELD_CONTRIBUTION_COUNT = "contributionCount"
FIELD_COLOR = "color"
FIELD_WEEKDAY = "weekday"
FIELD_CONTRIBUTION_YEARS = "contributionYears"

# Query node names
NODE_USER = "user"
NODE_VIEWER = "viewer"
NODE_WATCHING = "watching"
NODE_STARRED_REPOSITORIES = "starredRepositories"
NODE_FOLLOWING = "following"
NODE_FOLLOWERS = "followers"
NODE_GISTS = "gists"
NODE_ISSUES = "issues"
NODE_PROJECTS = "projects"
NODE_PULL_REQUESTS = "pullRequests"
NODE_REPOSITORIES = "repositories"
NODE_REPOSITORY_DISCUSSIONS = "repositoryDiscussions"
NODE_GIST_COMMENTS = "gistComments"
NODE_ISSUE_COMMENTS = "issueComments"
NODE_COMMIT_COMMENTS = "commitComments"
NODE_REPOSITORY_DISCUSSION_COMMENTS = "repositoryDiscussionComments"

NODE_CONTRIBUTIONS_COLLECTION = "contributionsCollection"
NODE_CONTRIBUTION_CALENDAR = "contributionCalendar"
NODE_WEEKS = "weeks"
NODE_CONTRIBUTION_DAYS = "contributionDays"

NODE_JOINED_GITHUB_CONTRIBUTION = "joinedGitHubContribution"
NODE_EDGES = "edges"
NODE_NODE = "node"
NODE_NODES = "nodes"
NODE_PAGE_INFO = "pageInfo"
NODE_LANGUAGES = "languages"
NODE_RATE_LIMIT = "rateLimit"

NODE_REPOSITORY = "repository"
NODE_PRIMARY_LANGUAGE = "primaryLanguage"
NODE_DEFAULT_BRANCH_REF = "defaultBranchRef"
NODE_TARGET = "target"
NODE_AUTHOR = "author"
NODE_HISTORY = "history"
NODE_ON = "... on "
NODE_COMMIT = "Commit"
NODE_PARENTS = "parents (first: 2)"

# Argument names for GraphQL queries
ARG_LOGIN = "login"
ARG_FIRST = "first"
ARG_IS_FORK = "isFork"
ARG_OWNER_AFFILIATIONS = "ownerAffiliations"
ARG_ORDER_BY = "orderBy"
ARG_FIELD = "field"
ARG_DIRECTION = "direction"
ARG_FROM = "from"
ARG_TO = "to"
ARG_DRYRUN = "dryRun"
ARG_OWNER = "owner"
ARG_NAME = "name"
ARG_AUTHOR = "author"
