"""add RepositoryDiscussion model

Revision ID: 059e46a9f61b
Revises: 29d71d1ae71b
Create Date: 2024-12-27 21:38:32.731612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059e46a9f61b'
down_revision = '29d71d1ae71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.String(length=80), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_discussions')
    # ### end Alembic commands ###
