"""Initial migration

Revision ID: 17094ed45005
Revises: 
Create Date: 2025-01-08 17:14:06.859008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17094ed45005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(length=80), nullable=False),
    sa.Column('github_login', sa.String(length=80), nullable=False),
    sa.Column('personal_access_token', sa.String(length=255), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('github_login')
    )
    op.create_table('user_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ds_name', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_queries')
    op.drop_table('users')
    # ### end Alembic commands ###
