"""add Gist model

Revision ID: 241170e32dfd
Revises: 87a9f2a990b7
Create Date: 2025-01-21 23:52:03.672632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241170e32dfd'
down_revision = '87a9f2a990b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gists')
    # ### end Alembic commands ###
