"""user userquery model

Revision ID: 3fbdb8532fdc
Revises: 
Create Date: 2025-01-20 12:36:11.250519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbdb8532fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(length=80), nullable=False),
    sa.Column('github_login', sa.String(length=80), nullable=False),
    sa.Column('personal_access_token', sa.String(length=255), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('github_login')
    )
    op.create_table('user_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=80), nullable=False),
    sa.Column('ds_name', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('queried_at', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_login'], ['users.github_login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_queries')
    op.drop_table('users')
    # ### end Alembic commands ###
