"""add User model

Revision ID: 44781a16b7d9
Revises: 
Create Date: 2024-12-27 19:23:17.179117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44781a16b7d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(length=80), nullable=False),
    sa.Column('github_login', sa.String(length=80), nullable=False),
    sa.Column('personal_access_token', sa.String(length=255), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('github_login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
