"""Update cascade deletion

Revision ID: 4dd971b4538c
Revises: c8eed7043c71
Create Date: 2025-01-21 19:51:45.047189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd971b4538c'
down_revision = 'c8eed7043c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commit_comments', schema=None) as batch_op:
        batch_op.drop_constraint('commit_comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_queries', ['user_query_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gist_comments', schema=None) as batch_op:
        batch_op.drop_constraint('gist_comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_queries', ['user_query_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('issue_comments', schema=None) as batch_op:
        batch_op.drop_constraint('issue_comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_queries', ['user_query_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('issue_comments_ibfk_1', 'user_queries', ['user_query_id'], ['id'])

    with op.batch_alter_table('gist_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gist_comments_ibfk_1', 'user_queries', ['user_query_id'], ['id'])

    with op.batch_alter_table('commit_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('commit_comments_ibfk_1', 'user_queries', ['user_query_id'], ['id'])

    # ### end Alembic commands ###
