"""add fields to commit

Revision ID: 87022104a3c0
Revises: ba7d976497ca
Create Date: 2025-02-03 15:04:15.108568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87022104a3c0'
down_revision = 'ba7d976497ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang_stats', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commits', schema=None) as batch_op:
        batch_op.drop_column('lang_stats')

    # ### end Alembic commands ###
