"""user userquery model

Revision ID: 878b85d6d1af
Revises: 3fbdb8532fdc
Create Date: 2025-01-20 23:56:56.206611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878b85d6d1af'
down_revision = '3fbdb8532fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comments')
    op.drop_table('commit_comments')
    # ### end Alembic commands ###
