"""add repo disscussion comment

Revision ID: 87a9f2a990b7
Revises: 4dd971b4538c
Create Date: 2025-01-21 20:07:03.491149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a9f2a990b7'
down_revision = '4dd971b4538c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_discussion_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_discussion_comments')
    # ### end Alembic commands ###
