"""add IssueComment model

Revision ID: 986e3db4d5b0
Revises: f5cbe6cc68f4
Create Date: 2024-12-27 19:42:48.838609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e3db4d5b0'
down_revision = 'f5cbe6cc68f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=80), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comments')
    # ### end Alembic commands ###
