"""add commit model

Revision ID: ba7d976497ca
Revises: 4352c9b469c6
Create Date: 2025-01-24 16:34:45.682362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d976497ca'
down_revision = '4352c9b469c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=80), nullable=True),
    sa.Column('author_name', sa.String(length=80), nullable=True),
    sa.Column('author_email', sa.String(length=80), nullable=True),
    sa.Column('author_login', sa.String(length=80), nullable=True),
    sa.Column('branch', sa.String(length=80), nullable=True),
    sa.Column('authored_date', sa.DateTime(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('parent_count', sa.Integer(), nullable=True),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commits')
    # ### end Alembic commands ###
