"""add Repository, Language model and association table

Revision ID: db856281182e
Revises: 059e46a9f61b
Create Date: 2024-12-28 00:59:05.971213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db856281182e'
down_revision = '059e46a9f61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('repository_id', sa.String(length=80), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('repository_type', sa.String(length=80), nullable=False),
    sa.Column('primary_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repository_languages',
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('repository_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_languages')
    op.drop_table('repositories')
    op.drop_table('languages')
    # ### end Alembic commands ###
