"""add Issue model

Revision ID: fcd56ad4b302
Revises: 3f381b20343a
Create Date: 2024-12-27 21:06:18.607741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd56ad4b302'
down_revision = '3f381b20343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###
