"""Add Commit and user_commit association table

Revision ID: fcf585d7154c
Revises: 539c1e5db2b0
Create Date: 2024-12-28 02:12:51.470768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf585d7154c'
down_revision = '539c1e5db2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.Column('authored_date', sa.DateTime(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=80), nullable=True),
    sa.Column('author_email', sa.String(length=80), nullable=True),
    sa.Column('author_login', sa.String(length=80), nullable=True),
    sa.Column('repo_owner_login', sa.String(length=80), nullable=True),
    sa.Column('repo_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_id')
    )
    op.create_table('user_commit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.commit_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'commit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_commit')
    op.drop_table('commits')
    # ### end Alembic commands ###
